name: Trigger auto deployment for selfedunet

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/selfedunet-AutoDeployTrigger-f111e2a1-71c9-4888-8b52-3e5ef5e62bd7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SELFEDUNET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SELFEDUNET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SELFEDUNET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: selfeduapp.azurecr.io
          registryUsername: ${{ secrets.SELFEDUNET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SELFEDUNET_REGISTRY_PASSWORD }}
          containerAppName: selfedunet
          resourceGroup: selfeduRG
          imageToBuild: selfeduapp.azurecr.io/selfedunet:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


